cred-section9-api:
  name: "Section 9 API"
  type: "username_password"
  env_prefix: "SECTION9"
  secret_keys:
    username: "USERNAME"
    password: "PASSWORD"

cred-github-token:
  name: "GitHub Token"
  type: "token"
  env_prefix: "GITHUB"
  secret_keys:
    token: "TOKEN"
